// client-code-snippets/svelte/code-templates/src/components/Address.svelte
{#if addresses}
  {#each addresses as address }
    <h1>{address.address}</h1>
  {/each}
{:else}
  <p class="loading">loading...</p>
{/if}

<script>
    import { onMount } from "svelte";
    import {fetchAPI} from '../api/fetchAPI';

    let addresses;
    onMount(async () => {
      await fetchAPI('/addresses')
          .then(r => r.json())
          .then(data => {
              addresses = data;
          });
      })
</script>

// client-code-snippets/react/code-templates/src/components/Address.js
import React, { Component } from 'react';
import {fetchAPI} from '../api/fetchApi';

export default class Address extends Component {
    state = {
        addresses: []
    }
    componentWillMount() {
        fetchAPI('/addresses')
            .then(res => res.json())
            .then(addresses => this.setState({ addresses }));
    }
    render() {
        return (
            <div>
                {this.state.addresses.map(address => {
                    return (
                        <h1 key={address.address}>{address.address}</h1>
                    )
                })}
            </div>
        )
    }
}
