// client-code-snippets/react/code-templates/src/App.js
import React, { Component } from 'react';
import ReactImage from './assets/react.png';
import './style.css';

export default class App extends Component {
  state = { username: null };

  componentDidMount() {
    fetch('/api/getUsername')
      .then(res => res.json())
      .then(user => this.setState({ username: user.username }));
  }

  render() {
    const { username } = this.state;
    return (
      <div>
        {username ? <h1>{`Hello there, I'm ${username}`}</h1> : <h1>Loading.. please wait!</h1>}
        <img src={ReactImage} alt="react" />
      </div>
    );
  }
}

// client-code-snippets/vue/code-templates/src/App.vue
<template>
  <div id="app">
    <img :src="logo" alt="Logo" />
    <h1 v-if="username === ''">Loading.. please wait!</h1>
    <h1 v-else>Hello there, I'm {{ username }}</h1>
  </div>
</template>

<script>
import logo from "./assets/logo.png";
export default {
  name: "App",
  data() {
    return {
      logo,
      username: ""
    };
  },
  mounted() {
    fetch("/api/getUsername")
      .then(res => res.json())
      .then(user => (this.username = user.username));
  }
};
</script>

<style lang="css" src="./style.css" />
